import { Component, type ReactNode, useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, CheckCircle, Star, X, Zap } from 'lucide-react'
import { ECONOMIA_STAGE } from '../../data/economiaCourse'
import { GEOMETRIA_COURSE, GEOMETRIA_STAGE, type AnswerChoice, type ExerciseQuestion } from '../../data/geometriaCourse'
import YordiGuide from '../../components/common/YordiGuide'
import { recordLearningAttempt } from '../../services/learningProgress'

type Answer = string | string[] | Record<string, string> | null
const shuffle = <T,>(items: T[]) => [...items].sort(() => Math.random() - 0.5)
const sameOrder = (a: string[], b: string[]) => a.length === b.length && a.every((value, index) => value === b[index])
const isCorrectAnswer = (question: ExerciseQuestion, answer: Answer) => {
  if (question.type === 'matching') return question.matching?.pairs.every((pair) => (answer as Record<string, string> | null)?.[pair.left.id] === pair.right.id) ?? false
  if (question.type === 'ordering') return Array.isArray(answer) && sameOrder(answer, question.ordering?.correctOrder || [])
  return typeof answer === 'string' && String(question.correctAnswer) === answer
}

class PracticeErrorBoundary extends Component<{ children: ReactNode }, { error: Error | null }> {
  state: { error: Error | null } = { error: null }
  static getDerivedStateFromError(error: Error) { return { error } }
  render() {
    if (!this.state.error) return this.props.children
    return <main className="mx-auto max-w-xl px-5 py-16 text-center"><div className="rounded-3xl border border-incorrect/30 bg-white p-8 shadow-card"><h1 className="text-2xl font-extrabold text-bark-800">No pudimos cargar esta pregunta</h1><p className="mt-3 text-sm font-semibold text-bark-500">Vuelve a la ruta y abre la lección otra vez. La práctica no se marcará como terminada.</p><p className="mt-5 rounded-xl bg-cream-50 p-3 text-left font-mono text-xs text-bark-500">{this.state.error.message}</p><button type="button" onClick={() => window.location.reload()} className="mt-6 rounded-xl bg-[#4B9B69] px-5 py-3 text-sm font-extrabold text-white">RECARGAR PRÁCTICA</button></div></main>
  }
}

function FppDiagram({ variant, alt }: { variant: 'basic' | 'growth' | 'contraction' | 'opportunity-cost'; alt: string }) {
  const shifted = variant === 'growth'; const contracted = variant === 'contraction'
  return <figure className="mt-5 rounded-2xl border border-[#B6D9C1] bg-[#F5FBF6] p-3"><svg viewBox="0 0 320 185" role="img" aria-label={alt} className="h-auto w-full"><line x1="42" y1="150" x2="294" y2="150" stroke="#896F54" strokeWidth="3" /><line x1="42" y1="150" x2="42" y2="22" stroke="#896F54" strokeWidth="3" /><text x="236" y="173" fill="#6A5746" fontSize="12">Bien X</text><text x="8" y="26" fill="#6A5746" fontSize="12">Bien Y</text><path d="M55 38 C118 55 175 96 278 142" fill="none" stroke="#4B9B69" strokeWidth="5" strokeLinecap="round" />{shifted && <path d="M55 19 C145 35 216 83 300 130" fill="none" stroke="#84C99C" strokeWidth="5" strokeLinecap="round" />}{contracted && <path d="M64 58 C118 73 159 105 237 140" fill="none" stroke="#D58B5C" strokeWidth="5" strokeLinecap="round" />}<circle cx={variant === 'basic' ? 155 : 193} cy={variant === 'basic' ? 91 : 104} r="7" fill="#FF5A72" />{variant === 'basic' && <><circle cx="111" cy="116" r="7" fill="#E7A958" /><circle cx="220" cy="57" r="7" fill="#8D7B6C" /><text x="98" y="135" fontSize="12">Interior</text><text x="208" y="48" fontSize="12">Exterior</text></>}{variant === 'opportunity-cost' && <><circle cx="105" cy="69" r="7" fill="#FF5A72" /><circle cx="223" cy="126" r="7" fill="#FF5A72" /><path d="M112 72 L214 122" stroke="#FF5A72" strokeWidth="2" strokeDasharray="5 5" /></>}<text x={variant === 'basic' ? 140 : 181} y={variant === 'basic' ? 82 : 95} fill="#5A4130" fontSize="12">Frontera</text></svg><figcaption className="mt-2 text-xs font-semibold text-bark-500">{alt}</figcaption></figure>
}

function AnswerButton({ choice, selected, answered, correct, onClick, showLetter = true }: { choice: AnswerChoice; selected: boolean; answered: boolean; correct: boolean; onClick: () => void; showLetter?: boolean }) {
  const index = choice.id.match(/-c(\d+)$/)?.[1] ?? (Number.isFinite(Number(choice.id)) ? String(Number(choice.id) + 1) : null)
  const state = answered ? correct ? 'border-correct bg-correct/10' : selected ? 'border-incorrect bg-incorrect/10' : 'border-bark-100 bg-cream-50 opacity-60' : selected ? 'border-[#4B9B69] bg-[#F0FAF3] ring-2 ring-[#D9F1E1]' : 'border-bark-100 bg-white hover:border-[#8BC9A2]'
  return <button type="button" disabled={answered} onClick={onClick} className={`flex w-full items-center gap-3 rounded-2xl border-2 px-4 py-3.5 text-left transition ${state}`}>{showLetter && <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-cream-100 text-xs font-extrabold text-bark-500">{index ? String.fromCharCode(65 + Number(index)) : '•'}</span>}<span className="flex-1 text-sm font-bold leading-relaxed text-bark-700">{choice.text}</span>{answered && correct && <CheckCircle size={18} className="text-correct" />}{answered && selected && !correct && <X size={18} className="text-incorrect" />}</button>
}

function EconomyPractice({ question, answer, setAnswer, answered, correct, onSubmit, onNext, isLast, shuffled }: { question: ExerciseQuestion; answer: Answer; setAnswer: (value: Answer) => void; answered: boolean; correct: boolean; onSubmit: () => void; onNext: () => void; isLast: boolean; shuffled: boolean }) {
  const [activeLeft, setActiveLeft] = useState<string | null>(null)
  useEffect(() => setActiveLeft(null), [question.id])
  const displayedChoices = useMemo(() => shuffled ? shuffle(question.choices || []) : question.choices || [], [question.id, question.choices, shuffled])
  const rightChoices = useMemo(() => shuffled ? shuffle(question.matching?.pairs.map((pair) => pair.right) || []) : question.matching?.pairs.map((pair) => pair.right) || [], [question.id, question.matching, shuffled])
  const orderingItems = useMemo(() => shuffled ? shuffle(question.ordering?.items || []) : question.ordering?.items || [], [question.id, question.ordering, shuffled])
  const resolution = question.resolutionSteps?.length ? question.resolutionSteps : [question.ideaKey || 'Identifica la idea central.', question.explanation]
  const selectedMap = (!Array.isArray(answer) && typeof answer === 'object' && answer) || {}
  const selectedOrder = Array.isArray(answer) ? answer : []
  const canSubmit = question.type === 'matching' ? Object.keys(selectedMap).length === (question.matching?.pairs.length || 0) : question.type === 'ordering' ? selectedOrder.length === (question.ordering?.items.length || 0) : answer !== null
  const correctText = question.type === 'word-bank' ? question.wordBank?.tokens.find((token) => token.id === question.wordBank?.correctTokenId)?.text : question.choices?.find((choice) => choice.id === question.correctAnswer)?.text
  return <main className="mx-auto max-w-[1120px] px-5 py-8 lg:px-8 lg:py-12"><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px] lg:items-start"><section className="min-w-0 rounded-[1.75rem] border border-bark-100 bg-white p-6 shadow-card sm:p-8"><p className="text-[11px] font-extrabold uppercase tracking-[0.15em] text-[#4B9B69]">Economía · práctica guiada</p><h1 className="mt-4 max-w-3xl font-display text-2xl font-extrabold leading-snug text-bark-900 sm:text-3xl">{question.question}</h1>{question.visual?.diagram?.type === 'fpp' && <FppDiagram variant={question.visual.diagram.variant} alt={question.visual.alt} />}<p className="mt-4 text-sm font-semibold text-bark-400">Elige o completa la respuesta antes de comprobar.</p>
    <div className="mt-7 space-y-3">{(question.type === 'multiple-choice' || question.type === 'true-false') && displayedChoices.map((choice) => <AnswerButton key={choice.id} choice={choice} selected={answer === choice.id} answered={answered} correct={choice.id === question.correctAnswer} onClick={() => setAnswer(choice.id)} showLetter={question.type !== 'true-false'} />)}
    {question.type === 'word-bank' && (() => { const bank = question.wordBank; if (!bank) return null; const selectedToken = bank.tokens.find((token) => token.id === answer)?.text || '________'; return <div className="space-y-4"><div className="rounded-2xl bg-cream-50 p-5 text-lg font-bold leading-relaxed text-bark-800">{bank.template.replace('{{respuesta}}', ` ${selectedToken} `)}</div><div className="flex flex-wrap gap-2">{bank.tokens.map((token) => <button key={token.id} type="button" disabled={answered} onClick={() => setAnswer(token.id)} className={`rounded-xl border-2 px-4 py-2.5 text-sm font-extrabold ${answer === token.id ? 'border-[#4B9B69] bg-[#F0FAF3] text-[#347A50]' : 'border-bark-100 bg-white text-bark-700'}`}>{token.text}</button>)}</div></div>})()}
    {question.type === 'matching' && <div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2">{question.matching?.pairs.map((pair) => <button key={pair.left.id} type="button" disabled={answered} onClick={() => setActiveLeft(pair.left.id)} className={`w-full rounded-xl border-2 p-3 text-left text-sm font-bold ${activeLeft === pair.left.id ? 'border-[#4B9B69] bg-[#F0FAF3]' : selectedMap[pair.left.id] ? 'border-[#B6D9C1] bg-[#F5FBF6]' : 'border-bark-100'}`}>{pair.left.text}{selectedMap[pair.left.id] && <span className="ml-2 text-xs text-[#4B9B69]">✓</span>}</button>)}</div><div className="space-y-2">{rightChoices.map((right) => <button key={right.id} type="button" disabled={answered || !activeLeft} onClick={() => activeLeft && (setAnswer({ ...selectedMap, [activeLeft]: right.id }), setActiveLeft(null))} className="w-full rounded-xl border-2 border-bark-100 p-3 text-left text-sm font-bold text-bark-700 disabled:opacity-50">{right.text}</button>)}</div></div>}
    {question.type === 'ordering' && <div className="space-y-3"><div className="min-h-14 rounded-2xl bg-cream-50 p-3">{selectedOrder.map((id, index) => <button key={id} type="button" disabled={answered} onClick={() => setAnswer(selectedOrder.filter((item) => item !== id))} className="mb-2 mr-2 rounded-xl bg-[#E6F4EA] px-3 py-2 text-sm font-bold text-[#347A50]">{index + 1}. {question.ordering?.items.find((item) => item.id === id)?.text}</button>)}</div><div className="flex flex-wrap gap-2">{orderingItems.filter((item) => !selectedOrder.includes(item.id)).map((item) => <button key={item.id} type="button" disabled={answered} onClick={() => setAnswer([...selectedOrder, item.id])} className="rounded-xl border-2 border-bark-100 px-3 py-2 text-sm font-bold">{item.text}</button>)}</div></div>}</div>
    <button type="button" onClick={answered ? onNext : onSubmit} disabled={!answered && !canSubmit} className="mt-7 w-full rounded-2xl bg-[#4B9B69] py-3.5 text-sm font-extrabold text-white shadow-[0_4px_0_#367E53] disabled:cursor-not-allowed disabled:bg-bark-100 disabled:text-bark-300 disabled:shadow-none">{answered ? (isLast ? 'VER RESULTADO' : 'CONTINUAR') : 'COMPROBAR'}</button></section>
    <aside className="lg:sticky lg:top-24">{!answered ? <div className="rounded-[1.5rem] border border-bark-100 bg-cream-50 p-5 text-sm font-semibold leading-relaxed text-bark-500">Responde primero. Aquí verás por qué una alternativa es correcta.</div> : <div className={`rounded-[1.5rem] border p-5 ${correct ? 'border-correct/25 bg-correct/5' : 'border-incorrect/25 bg-incorrect/5'}`}><div className="flex items-center gap-2 text-sm font-extrabold text-bark-800">{correct ? <CheckCircle size={19} className="text-correct" /> : <X size={19} className="text-incorrect" />}{correct ? 'Respuesta correcta' : 'Revisa esta idea'}</div>{correctText && <><p className="mt-4 text-xs font-extrabold uppercase tracking-[0.12em] text-bark-400">Respuesta</p><p className="mt-1 text-sm font-extrabold text-bark-800">{correctText}</p></>}<p className="mt-4 text-sm font-semibold leading-relaxed text-bark-600">{question.explanation}</p><div className="mt-4 rounded-xl bg-white/70 p-3"><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#4B9B69]">Idea clave</p><p className="mt-1 text-sm font-bold leading-relaxed text-bark-700">{question.ideaKey}</p></div><ol className="mt-4 space-y-2 border-t border-bark-100 pt-4 text-sm font-semibold leading-relaxed text-bark-600">{resolution.map((item, index) => <li key={item}><span className="mr-1 font-extrabold text-[#4B9B69]">{index + 1}.</span>{item}</li>)}</ol></div>}</aside></div></main>
}

export default function LessonPage() {
  const { nodeId, lessonId } = useParams<{ nodeId: string; lessonId: string }>(); const navigate = useNavigate()
  const economyNode = ECONOMIA_STAGE.sections.flatMap((unit) => unit.nodes).find((node) => node.id === nodeId)
  const courseId = economyNode ? 'economia' : 'geometria'; const node = economyNode || GEOMETRIA_COURSE.flatMap((unit) => unit.nodes).find((item) => item.id === nodeId); const lesson = node?.lessons.find((item) => item.id === lessonId)
  const sections = economyNode ? ECONOMIA_STAGE.sections : GEOMETRIA_STAGE.sections; const sectionId = sections.find((section) => section.nodes.some((item) => item.id === nodeId))?.id || sections[0].id; const returnToCourse = `/courses/${courseId}?section=${sectionId}`
  const repeated = useMemo(() => { try { return JSON.parse(localStorage.getItem('cuiz-learning-attempts') || '[]').some((attempt: { lessonId: string }) => attempt.lessonId === lessonId) } catch { return false } }, [lessonId])
  const steps = useMemo(() => lesson ? (repeated && courseId === 'economia' ? shuffle(lesson.exercises) : lesson.exercises) : [], [lesson, repeated, courseId])
  const [index, setIndex] = useState(0); const [answer, setAnswer] = useState<Answer>(null); const [answered, setAnswered] = useState(false); const [correct, setCorrect] = useState(false); const [xp, setXp] = useState(0); const [correctCount, setCorrectCount] = useState(0); const [done, setDone] = useState(false)
  useEffect(() => { setIndex(0); setAnswer(null); setAnswered(false); setDone(false) }, [lessonId]); useEffect(() => window.scrollTo(0, 0), [index, done])
  if (!node || !lesson || !steps.length) return <div className="flex min-h-full items-center justify-center bg-cream-100 text-bark-500">Lección no encontrada</div>
  const question = steps[index]; const progress = done ? 100 : Math.max(8, ((index + 1) / steps.length) * 100)
  const submit = () => { if (!isCorrectAnswer(question, answer) && answer === null) return; const result = isCorrectAnswer(question, answer); setCorrect(result); setAnswered(true); recordLearningAttempt({ courseId, nodeId: nodeId || '', lessonId: lessonId || '', questionId: question.id, correct: result }); if (result) { setXp((value) => value + 10); setCorrectCount((value) => value + 1) } }
  const next = () => { if (index < steps.length - 1) { setIndex(index + 1); setAnswer(null); setAnswered(false); setCorrect(false); return } const completed = JSON.parse(localStorage.getItem(`completed-lessons-${nodeId}`) || '[]'); if (!completed.includes(lessonId)) localStorage.setItem(`completed-lessons-${nodeId}`, JSON.stringify([...completed, lessonId])); setDone(true) }
  const legacyChoices = (question.options || []).map((text, index) => ({ id: String(index), text }))
  return <div className="min-h-full bg-cream-100 pb-20 lg:pb-8"><header className="sticky top-0 z-20 border-b border-bark-100/80 bg-cream-50/95 px-4 py-3 backdrop-blur lg:px-8"><div className="mx-auto flex max-w-7xl items-center gap-3"><button type="button" onClick={() => navigate(returnToCourse)} className="rounded-xl p-2 text-bark-500" aria-label="Volver"><ArrowLeft size={21} /></button><div className="flex-1"><div className="h-2.5 overflow-hidden rounded-full bg-bark-100"><div className={`h-full rounded-full ${courseId === 'economia' ? 'bg-[#4B9B69]' : 'bg-primary-400'}`} style={{ width: `${progress}%` }} /></div><p className="mt-1 text-[10px] font-bold text-bark-400">{done ? 'Lección completada' : `Pregunta ${index + 1} de ${steps.length}`}</p></div><div className="flex items-center gap-1 rounded-xl bg-xp/10 px-2 py-1 text-sm font-extrabold text-bark-700"><Zap size={16} className="text-xp" />{xp}</div></div></header>
    {!done && courseId === 'economia' && <PracticeErrorBoundary><EconomyPractice question={question} answer={answer} setAnswer={setAnswer} answered={answered} correct={correct} onSubmit={submit} onNext={next} isLast={index === steps.length - 1} shuffled={repeated} /></PracticeErrorBoundary>}
    {!done && courseId === 'geometria' && <main className="mx-auto max-w-4xl px-5 py-10"><div className="rounded-3xl bg-white p-7 shadow-card"><p className="text-xs font-extrabold text-primary-500">GEOMETRÍA · PRÁCTICA</p><h1 className="mt-4 text-3xl font-extrabold text-bark-800">{question.question}</h1><div className="mt-7 space-y-3">{legacyChoices.map((choice) => <AnswerButton key={choice.id} choice={choice} selected={answer === choice.id} answered={answered} correct={choice.id === String(question.correctAnswer)} onClick={() => setAnswer(choice.id)} />)}</div>{answered && <p className="mt-5 rounded-2xl bg-primary-50 p-4 font-semibold text-bark-700">{question.explanation}</p>}<button type="button" onClick={answered ? next : submit} disabled={!answered && answer === null} className="mt-6 w-full rounded-2xl bg-primary-400 py-4 font-extrabold text-white disabled:bg-bark-100">{answered ? (index === steps.length - 1 ? 'VER RESULTADO' : 'CONTINUAR') : 'COMPROBAR'}</button></div></main>}
    {done && <main className="mx-auto max-w-2xl px-5 py-12 text-center">{courseId === 'geometria' && <YordiGuide size="lg" message="¡Terminaste tu misión geométrica!" className="justify-center" />}<div className="mx-auto mt-6 flex h-20 w-20 items-center justify-center rounded-full bg-xp/15"><Star size={42} className="text-xp" fill="currentColor" /></div><h1 className="mt-5 text-3xl font-extrabold text-bark-800">¡Excelente trabajo!</h1><p className="mt-2 text-bark-500">Terminaste la práctica de {lesson.title.toLowerCase()}.</p><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white p-4 shadow-card"><p className="text-2xl font-extrabold text-correct">{correctCount}/{steps.length}</p><p className="text-xs font-semibold text-bark-400">Correctas</p></div><div className="rounded-2xl bg-white p-4 shadow-card"><p className="text-2xl font-extrabold text-xp">+{xp}</p><p className="text-xs font-semibold text-bark-400">XP ganados</p></div></div><button type="button" onClick={() => navigate(returnToCourse)} className="mt-7 w-full rounded-2xl bg-primary-400 py-3.5 text-sm font-extrabold text-white">VOLVER A MI RUTA</button></main>}</div>
}
