import { BarChart3, BookOpen, Calculator, FileText, Layers, Library, LockKeyhole, Presentation, X } from 'lucide-react'
import type { CourseResource, GeometrySection, GeometryStage, SectionResource } from '../../data/geometriaCourse'

export type SectionResourceView = 'summary' | 'flashcards' | 'more'

export function GeometryToolbar({ stage, sections, selectedSectionId, onSectionSelect, onOpenPerformance, courseName = 'Geometría', sectionLabel = 'Sección' }: { stage: Pick<GeometryStage, 'title'>; sections: Array<Pick<GeometrySection, 'id' | 'title'>>; selectedSectionId: string; onSectionSelect: (id: string) => void; onOpenPerformance?: () => void; courseName?: string; sectionLabel?: string }) {
  return <div className="sticky top-0 z-30 -mx-4 mb-6 border-y border-bark-100/80 bg-cream-100/95 px-4 py-3 backdrop-blur-md sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8"><div className="mx-auto flex max-w-[1120px] items-center gap-3"><div className="hidden shrink-0 sm:block"><p className="text-[10px] font-extrabold uppercase tracking-[0.14em] text-primary-500">{stage.title}</p><p className="text-sm font-extrabold text-bark-800">{courseName} · Etapa 1</p></div><label className="min-w-0 flex-1"><span className="sr-only">{sectionLabel} activa</span><select value={selectedSectionId} onChange={(event) => onSectionSelect(event.target.value)} className="w-full rounded-2xl border border-bark-100 bg-white px-3 py-2.5 text-sm font-extrabold text-bark-700 shadow-sm outline-none focus:border-primary-300 focus:ring-2 focus:ring-primary-100">{sections.map((section, index) => <option key={section.id} value={section.id}>{sectionLabel} {index + 1} · {section.title}</option>)}</select></label>{onOpenPerformance && <button type="button" onClick={onOpenPerformance} className="inline-flex shrink-0 items-center gap-2 rounded-2xl bg-primary-500 px-3.5 py-2.5 text-sm font-extrabold text-white shadow-[0_3px_0_#D63E59] transition hover:-translate-y-0.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-300"><BarChart3 size={17} /><span className="hidden sm:inline">Mi desempeño</span><span className="sm:hidden">Mapa</span></button>}</div></div>
}

function iconFor(type: CourseResource['type'] | SectionResource['type']) { if (type === 'syllabus') return FileText; if (type === 'slides') return Presentation; if (type === 'books') return Library; if (type === 'formulas') return Calculator; return Layers }

export function CourseResourcesDialog({ section, resources, view, onClose, onOpenSyllabus }: { section: GeometrySection | null; resources: CourseResource[]; view: SectionResourceView | null; onClose: () => void; onOpenSyllabus: () => void }) {
  if (!section || !view) return null
  const material = section.studyMaterial
  const title = view === 'summary' ? 'Resumen' : view === 'flashcards' ? 'Flashcards' : 'Más recursos'
  return <div className="fixed inset-0 z-[70] flex items-end justify-center bg-bark-900/35 p-3 backdrop-blur-sm sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-label={`${title} de ${section.title}`}><section className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-[2rem] bg-white p-5 shadow-[0_20px_50px_rgba(61,43,31,0.2)] sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.15em] text-primary-500">{title} · {section.title}</p><h2 className="mt-1 font-display text-2xl font-extrabold text-bark-800">{view === 'summary' ? 'Lo esencial de la sección' : view === 'flashcards' ? 'Repasa a tu ritmo' : 'Material para profundizar'}</h2></div><button type="button" onClick={onClose} aria-label="Cerrar" className="flex h-10 w-10 items-center justify-center rounded-xl bg-cream-100 text-bark-500"><X size={20} /></button></div>
    {view === 'summary' && <article className="mt-7 rounded-2xl border border-primary-100 bg-primary-50 p-5"><div className="flex items-center gap-2 text-primary-600"><BookOpen size={19} /><h3 className="font-extrabold">Resumen de {section.title}</h3></div><p className="mt-3 text-sm font-semibold leading-relaxed text-bark-700">{material.summary}</p><div className="mt-4 space-y-2">{material.keyIdeas.map((idea) => <p key={idea} className="rounded-xl bg-white px-3 py-2 text-sm font-semibold text-bark-600">{idea}</p>)}</div></article>}
    {view === 'flashcards' && <div className="mt-7 space-y-3">{material.flashcards.map((card, index) => <details key={card.question} className="rounded-2xl border border-bark-100 bg-cream-50 p-4"><summary className="cursor-pointer list-none text-sm font-extrabold text-bark-800"><span className="mr-2 text-primary-500">{index + 1}.</span>{card.question}</summary><p className="mt-3 text-sm font-semibold leading-relaxed text-bark-600">{card.answer}</p>{card.hint && <p className="mt-2 text-xs font-bold text-primary-600">Pista: {card.hint}</p>}</details>)}</div>}
    {view === 'more' && <><h3 className="mt-7 text-xs font-extrabold uppercase tracking-[0.14em] text-bark-400">De esta sección</h3><ResourceGrid resources={material.resources} onOpenSyllabus={onOpenSyllabus} /><h3 className="mt-7 text-xs font-extrabold uppercase tracking-[0.14em] text-bark-400">Recursos generales de Geometría</h3><ResourceGrid resources={resources} onOpenSyllabus={onOpenSyllabus} /></>}
  </section></div>
}

function ResourceGrid({ resources, onOpenSyllabus }: { resources: Array<CourseResource | SectionResource>; onOpenSyllabus: () => void }) { return <div className="mt-2 grid gap-2 sm:grid-cols-2">{resources.map((resource) => { const Icon = iconFor(resource.type); const available = resource.status === 'available'; const opensSyllabus = available && 'href' in resource && Boolean(resource.href); return <button key={resource.id} type="button" disabled={!available} onClick={opensSyllabus ? onOpenSyllabus : undefined} className={`flex items-center gap-3 rounded-2xl border p-3 text-left transition ${available ? 'border-primary-100 bg-white hover:border-primary-300 hover:bg-primary-50' : 'cursor-not-allowed border-bark-100 bg-bark-50/70 opacity-70'}`}><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${available ? 'bg-primary-50 text-primary-500' : 'bg-bark-100 text-bark-400'}`}>{available ? <Icon size={17} /> : <LockKeyhole size={16} />}</span><span className="min-w-0"><span className="block text-sm font-extrabold text-bark-700">{resource.title}</span><span className="mt-0.5 block text-xs font-semibold text-bark-400">{available ? resource.description : 'Próximamente'}</span></span></button> })}</div> }
