import { ArrowLeft, ArrowRight, CheckCircle2, CircleDashed, Sparkles, Target } from 'lucide-react'
import { Link } from 'react-router-dom'
import { getGeometryPerformance, getGeometryRecommendation } from '../../services/learningProgress'

const statusCopy = {
  mastered: { label: 'Dominado', className: 'bg-correct/10 text-correct', icon: CheckCircle2 },
  completed: { label: 'Completado', className: 'bg-[#EEF1FF] text-[#657FD1]', icon: CheckCircle2 },
  'in-progress': { label: 'En práctica', className: 'bg-[#FFF1DD] text-[#C88924]', icon: CircleDashed },
  available: { label: 'Sin practicar', className: 'bg-bark-100 text-bark-500', icon: Target },
}

export default function GeometryPerformance() {
  const topics = getGeometryPerformance(true)
  const recommendation = getGeometryRecommendation()
  const groups = { mastered: topics.filter((topic) => topic.status === 'mastered'), progress: topics.filter((topic) => topic.status === 'in-progress' || topic.status === 'completed'), reinforce: topics.filter((topic) => topic.status === 'in-progress' && topic.accuracy < 80) }
  return <main className="min-h-full bg-cream-100 px-4 py-7 sm:px-8"><div className="mx-auto max-w-5xl"><Link to="/courses/geometria" className="inline-flex items-center gap-2 text-sm font-extrabold text-bark-500 hover:text-primary-500"><ArrowLeft size={17} />Volver a Geometría</Link><header className="mt-7"><p className="flex items-center gap-2 text-[11px] font-extrabold uppercase tracking-[0.16em] text-primary-500"><Sparkles size={15} />Mi desempeño</p><h1 className="mt-2 font-display text-3xl font-extrabold text-bark-900 sm:text-4xl">Tu mapa de Geometría</h1><p className="mt-2 max-w-2xl text-sm font-semibold leading-relaxed text-bark-500">No es una nota final: te ayuda a decidir dónde invertir tu siguiente sesión.</p></header><section className="mt-7 rounded-[1.75rem] bg-gradient-to-r from-primary-400 to-[#F04462] p-5 text-white shadow-md"><p className="text-[10px] font-extrabold uppercase tracking-[0.15em] text-white/75">Prioridad sugerida</p><h2 className="mt-1 font-display text-xl font-extrabold">{recommendation.title}</h2><p className="mt-1 text-sm font-semibold text-white/85">{recommendation.description}</p></section><div className="mt-6 grid gap-4 sm:grid-cols-3"><Stat label="Dominados" value={groups.mastered.length} tone="text-correct" /><Stat label="En práctica" value={groups.progress.length} tone="text-[#C88924]" /><Stat label="Por reforzar" value={groups.reinforce.length} tone="text-primary-500" /></div><section className="mt-7 rounded-[1.75rem] border border-bark-100 bg-white p-5 shadow-card sm:p-7"><h2 className="font-display text-2xl font-extrabold text-bark-800">Temas de Geometría</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{topics.map((topic) => { const config = statusCopy[topic.status]; const Icon = config.icon; return <article key={topic.nodeId} className="rounded-2xl bg-cream-50 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-extrabold text-bark-800">{topic.title}</h3><span className={`mt-2 inline-flex items-center gap-1 rounded-full px-2 py-1 text-[10px] font-extrabold ${config.className}`}><Icon size={12} />{config.label}</span></div>{topic.total > 0 && <span className="text-sm font-extrabold text-bark-600">{topic.accuracy}%</span>}</div><p className="mt-3 text-xs font-semibold text-bark-500">{topic.total ? `${topic.correct}/${topic.total} respuestas recientes correctas.` : 'Aún no hay evidencia de práctica.'}</p><Link to={`/courses/geometria?section=${topic.sectionId}`} className="mt-3 inline-flex items-center gap-1 text-xs font-extrabold text-primary-600">Ver en el árbol <ArrowRight size={13} /></Link></article> })}</div></section></div></main>
}

function Stat({ label, value, tone }: { label: string; value: number; tone: string }) { return <div className="rounded-2xl border border-bark-100 bg-white p-5"><p className={`text-3xl font-extrabold ${tone}`}>{value}</p><p className="mt-1 text-xs font-extrabold uppercase tracking-wide text-bark-500">{label}</p></div> }
